app.name: AMV Access API
app.description: AMV Access API Gateway

debug: true

spring.profiles.active: production
spring.application.name: ${app.name} (${spring.profiles.active})

#spring.jpa.database-platform: 'org.amv.access.sqlite.SQLiteDialect'
#spring.jpa.hibernate.ddl-auto: 'validate' #'update'
#spring.jpa.show-sql: false

server.context-path: /amv-access-api
server.port: 9000
server.use-forward-headers: true
server.compression.enabled: true

#security.user.name: john_doe
#security.user.password: mysupersecretpassword

management.security.enabled: false
management.port: 9001
management.context-path: /manage

logging.config: classpath:logback-spring.xml

flyway.enabled: true
flyway.locations: 'db/migration/sqlite'

amv.access.database:
  driverClassName: 'org.sqlite.JDBC'
  url: 'jdbc:sqlite:amv-access.db?journal_mode=wal'
  pool-name: 'amv-access-sqlite-connection-pool'
  maximum-pool-size: 10
  column-encryption-key: 'MySuperSecretKey'

amv.issuer:
  name: XXXX
  public-key: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  private-key: BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

amv.swagger:
  enabled: true
  version: '0.0.1-SNAPSHOT'
  title: 'AMV Access API'
  description: |
    The AMV Access API interface definition
    Generate Device and Access Certficates as you please

  termsOfServiceUrl: 'API Terms Of Service'
  license: 'Apache License 2.0'
  licenseUrl: 'https://opensource.org/licenses/Apache-2.0'
  contact-name: 'AMV Networks GmbH'
  contact-url: 'https://www.amv-networks.com'
  contact-email: 'support@amv-networks.com'

amv.access.demo:
  enabled: true
  issuer:
     name: 'DEMO'
     publicKeyBase64: 'qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqg=='
     privateKeyBase64: 'u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7s='
  vehicles:
   - name: 'TEST-VEHICLE-1'
     serialNumber: '0000073cbc01354c9c'
     publicKeyBase64: 'HmXjzb0VJXf98p7F6gYiIAs0DHP6UlAKJSwHNBLeGIFNe6pYdW7e7HAXCNWJsI4tIOSnfn8uJ0ERv1CnQjZAww=='
   - name: 'TEST-VEHICLE-2'
     serialNumber: '00000fe5ad48c04a1d'
     publicKeyBase64: 'QJ+HNttBcWryKJfrlkH8EfZkR/7uDCdZgIC0vkthqVNxZ51Q6tsh20mNPPWFlhPGgXau+LZm/O44btkkmLxgSA=='
  applications:
   - name: 'DEMO-APP-1'
     appId: '9ff545aa4d4e662e636ca9a4'
     apiKey: 'demo-app-1-api-key'
   - name: 'DEMO-APP-2'
     appId: '00000e542a7a7a110f856b88'
     apiKey: 'demo-app-2-api-key'

